-- Expand Discover / suggestions so the list stays full after filtering owned tickers

INSERT INTO symbols (symbol, name, exchange, currency) VALUES
  ('AAPL', 'Apple Inc', 'US', 'USD'),
  ('MSFT', 'Microsoft Corp', 'US', 'USD'),
  ('NVDA', 'NVIDIA Corp', 'US', 'USD'),
  ('GOOGL', 'Alphabet Inc', 'US', 'USD'),
  ('AMZN', 'Amazon.com Inc', 'US', 'USD'),
  ('TSLA', 'Tesla Inc', 'US', 'USD'),
  ('META', 'Meta Platforms Inc', 'US', 'USD'),
  ('BRK.B', 'Berkshire Hathaway Inc', 'US', 'USD'),
  ('JPM', 'JPMorgan Chase & Co', 'US', 'USD'),
  ('V', 'Visa Inc', 'US', 'USD'),
  ('UNH', 'UnitedHealth Group Inc', 'US', 'USD'),
  ('XOM', 'Exxon Mobil Corp', 'US', 'USD'),
  ('JNJ', 'Johnson & Johnson', 'US', 'USD'),
  ('WMT', 'Walmart Inc', 'US', 'USD'),
  ('MA', 'Mastercard Inc', 'US', 'USD'),
  ('PG', 'Procter & Gamble Co', 'US', 'USD'),
  ('HD', 'Home Depot Inc', 'US', 'USD'),
  ('COST', 'Costco Wholesale Corp', 'US', 'USD'),
  ('ABBV', 'AbbVie Inc', 'US', 'USD'),
  ('CRM', 'Salesforce Inc', 'US', 'USD'),
  ('AMD', 'Advanced Micro Devices Inc', 'US', 'USD'),
  ('NFLX', 'Netflix Inc', 'US', 'USD'),
  ('BAC', 'Bank of America Corp', 'US', 'USD'),
  ('KO', 'Coca-Cola Co', 'US', 'USD'),
  ('PEP', 'PepsiCo Inc', 'US', 'USD'),
  ('DIS', 'Walt Disney Co', 'US', 'USD'),
  ('INTC', 'Intel Corp', 'US', 'USD'),
  ('CSCO', 'Cisco Systems Inc', 'US', 'USD'),
  ('ORCL', 'Oracle Corp', 'US', 'USD'),
  ('ADBE', 'Adobe Inc', 'US', 'USD')
ON CONFLICT (symbol) DO NOTHING;

INSERT INTO suggested_symbols (symbol, sort_order, label) VALUES
  ('AAPL', 1, 'Popular'),
  ('NVDA', 2, 'Popular'),
  ('MSFT', 3, 'Popular'),
  ('GOOGL', 4, 'Trending'),
  ('TSLA', 5, 'Trending'),
  ('AMZN', 6, 'Popular'),
  ('META', 7, 'Popular'),
  ('JPM', 8, NULL),
  ('AMD', 9, 'Trending'),
  ('NFLX', 10, 'Popular'),
  ('COST', 11, NULL),
  ('CRM', 12, NULL),
  ('V', 13, NULL),
  ('MA', 14, NULL),
  ('WMT', 15, NULL),
  ('HD', 16, NULL),
  ('BAC', 17, NULL),
  ('XOM', 18, NULL),
  ('DIS', 19, NULL),
  ('KO', 20, NULL),
  ('PEP', 21, NULL),
  ('ORCL', 22, NULL),
  ('ADBE', 23, NULL),
  ('INTC', 24, NULL),
  ('CSCO', 25, NULL),
  ('UNH', 26, NULL),
  ('JNJ', 27, NULL),
  ('PG', 28, NULL),
  ('ABBV', 29, NULL),
  ('BRK.B', 30, NULL)
ON CONFLICT (symbol) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  label = COALESCE(EXCLUDED.label, suggested_symbols.label);
